CREATE TABLE PHONEINFO_BASIC(
    IDX NUMBER(6) CONSTRAINT PB_IDX_PK PRIMARY KEY NOT NULL,
    FR_NAME VARCHAR2(20) NOT NULL,
    FR_PHONENUMBER VARCHAR2(20) NOT NULL,
    FR_EMAIL VARCHAR2(20),
    FR_ADDRESS VARCHAR2(20) ,
    FR_REGDATE DATE DEFAULT SYSDATE
);
DESC PHONEINFO_BASIC;
DROP TABLE PHONEINFO_BASIC;

CREATE TABLE PHONEINFO_UNIV(
    IDX NUMBER(6) ,
    FR_U_MAJOR VARCHAR2(20) DEFAULT 'N' NOT NULL,
    FR_U_YEAR NUMBER(1) DEFAULT 1 NOT NULL,
    FR_REF NUMBER(7)NOT NULL ,
    
    CONSTRAINT PU_IDX_PK PRIMARY KEY (idx),
    CONSTRAINT CK CHECK (FR_U_YEAR BETWEEN 1 AND 4),
    CONSTRAINT PU_REF_FK FOREIGN KEY(FR_REF)REFERENCES PHONEINFO_BASIC(IDX)  
);
DESC PHONEINFO_UNIV;
DROP TABLE PHONEINFO_UNIV;

CREATE TABLE PHONEINFO_COM(
    IDX NUMBER(6) NOT NULL PRIMARY KEY,
    FR_C_COMPANY VARCHAR2(20)DEFAULT 'N'  NOT NULL,
    FR_REF NUMBER(6) CONSTRAINT PC_FREF_FK REFERENCES PHONEINFO_BASIC(IDX)NOT NULL 
);
DESC PHONEINFO_COM;
DROP TABLE PHONEINFO_COM;