CREATE TABLE PHONEINFO_BASIC(
    IDX NUMBER(6) CONSTRAINT PB_IDX_PK PRIMARY KEY NOT NULL,
    FR_NAME VARCHAR2(20) NOT NULL,
    FR_PHONENUMBER VARCHAR2(20) NOT NULL,
    FR_EMAIL VARCHAR2(20),
    FR_ADDRESS VARCHAR2(20) ,
    FR_REGDATE DATE DEFAULT SYSDATE
);
DESC PHONEINFO_BASIC;
DROP TABLE PHONEINFO_BASIC;

CREATE TABLE PHONEINFO_UNIV(
    IDX NUMBER(6) CONSTRAINT PU_IDX_PK PRIMARY KEY NOT NULL,
    FR_U_MAJOR VARCHAR2(20) DEFAULT 'N' NOT NULL,
    FR_U_YEAR NUMBER(1) DEFAULT 1 CONSTRAINT PU_FUYEAR_CK CHECK (YEAR BETWEEN 2 AND 4) NOT NULL ,
    FR_REF NUMBER(7)CONSTRAINT PU_REF_FK REFERENCES PHONEINFO_BASIC(IDX)  NOT NULL 
);
DESC PHONEINFO_UNIV;
DROP TABLE PHONEINFO_UNIV;

CREATE TABLE PHONEINFO_COM(
    IDX NUMBER(6) NOT NULL PRIMARY KEY,
    FR_C_COMPANY VARCHAR2(20)DEFAULT 'N'  NOT NULL,
    FR_REF NUMBER(6) CONSTRAINT PC_FREF_FK REFERENCES PHONEINFO_BASIC(IDX)NOT NULL 
);
DESC PHONEINFO_COM;
DROP TABLE PHONEINFO_COM;